name: Build Library

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-lib.yaml'
      - 'src/**'

jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build
        run: |
          mvn clean install package

      - name: Upload to GitHub Packages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: pin-generator
          path: target/pin-generator-*.jar
